<a href="https://colab.research.google.com/github/DanielFHurtado/Matrices/blob/main/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ejercicio 1: Eliminacion de Gauss

In [ ]:
import numpy as np

# Matriz de coeficientes
A = np.array ([[2, 3, 1],
               [4, 1, 2],
               [3, 4, 2]], dtype=float)

# Vector de terminos independientes
b = np.array([0.5, 1, 1.5], dtype=float)

# Resolviendo el sistema de ecuaciones usando eliminacion de Gauss
sol = np.linalg.solve(A, b)

# Mostrar la solución
print("Soluucion del sistema:")
print(f"x = {sol[0]:.4f}, y = {sol[1]:.4f}, z = {sol[2]:.4f}")

Soluucion del sistema:
x = -1.0000, y = -0.0000, z = 3.0000


Ejercicio 2: Matriz Inversa

In [ ]:
import numpy as np

# Matriz de coeficientes
A = np.array ([[3, -0.1, -0.2],
               [0.1, 0.7, -0.3],
               [0.3, -0.2, 10]], dtype=float)

# Vector de salida deseada
b = np.array([7.85, 19.3, 71.4], dtype=float)

# Resolviendo el sistema de ecuaciones usando eliminacion de Gauss
A_inv = np.linalg.inv(A)

sol = np.dot(A_inv, b)

# Mostrar la solución
print("Pesos ajustados:")
print(f"w1 = {sol[0]:.4f}, w2 = {sol[1]:.4f}, w3 = {sol[2]:.4f}")

Pesos ajustados:
w1 = 1.7500, w2 = 0.3000, w3 = 0.5500


Ejercicio 3: Metodo de Jacobi

In [ ]:
import numpy as np

def jacobi(A, b, x0, tol=1e-10, max_iter=1000):
    n = len(b)
    x = x0
    for k in range(max_iter):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if i != j)
            x_new[i] = (b[i] - s) / A[i][i]
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new
        x = x_new
    return x

# Matriz de coeficientes
A = np.array([[3, -0.1, -0.2],
               [0.1, 0.7, -0.3],
               [0.3, -0.2, 10]], dtype=float)

# Vector de errores
b = np.array([7.85, 19.3, 71.4], dtype=float)

# Aproximación inicial
x0 = np.zeros_like(b)

# Aplicar el método de Jacobi
sol = jacobi(A, b, x0)

print("Pesos ajustados usando Jacobi:")
print(sol)


Pesos ajustados usando Jacobi:
[0.03201923 0.15923077 0.21951923]


Ejercicio 4: Método Iterativo de Gauss-Seidel

In [ ]:
import numpy as np

def gauss_seidel(A, b, x0, tol=1e-10, max_iter=1000):
    n = len(b)
    x = x0
    for k in range(max_iter):
        x_new = np.copy(x)
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i+1, n))
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
    return x, max_iter

# Matriz de coeficientes
A = np.array([[10, -1, 2],
              [-1, 11, -1],
              [2, -1, 10]], dtype=float)

# Vector de términos independientes
b = np.array([5, 6, 7], dtype=float)

# Valor inicial de las incógnitas
x0 = np.zeros_like(b)

# Resolver el sistema usando el método de Gauss-Seidel
sol, iteraciones = gauss_seidel(A, b, x0)

# Mostrar la solución y el número de iteraciones
print("Solución del sistema:")
print(sol)
print(f"Número de iteraciones: {iteraciones}")

Solución del sistema:
[ 1.  2. -1.  1.]
Número de iteraciones: 11


Ejercicio 5: Descomposicion de Cholesky

In [ ]:
from scipy.linalg import cholesky

# Matriz y vector
A = np.array([[25, 15, -5],
              [15, 18, 0],
              [-5, 0, 11]], dtype=float)

b = np.array([350, 400, 200], dtype=float)

# Descomposición de Cholesky
L = cholesky(A, lower=True)

# Resolver Ly = b
y = np.linalg.solve(L, b)

# Resolver L^T x = y
x = np.linalg.solve(L.T, y)

print("Pesos ajustados usando Cholesky:")
print(x)


Pesos ajustados usando Cholesky:
[1. 1. 1.]
